---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-log-pipeline
  namespace: beats
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: logstash
        image: asia.gcr.io/csw-stg1/logstash-log-pipeline:latest
