apiVersion: v1
kind: ConfigMap
metadata:
  name: timecard
  namespace: timecard
data:
  db_user: "postgres"
  db_name: "timecard"
  db_pass: 12345
  redis_addr: "redis:6379"
  redis_pass: 12345
  node_env: "development"