apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timecard
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-notifications
spec:
  project: default
  source:
    repoURL: 'https://github.com/my-org/my-app'
    targetRevision: main
    path: k8s/helm/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
