---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-filebeat
  namespace: beats
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.shutdown_timeout: 5s

    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/lib/nginx-data/access.json*
        exclude_files: ['\.gz$']
        tags: ["access"]
      - type: log
        enabled: true
        paths:
          - /var/log/entry-log/action.json*
        exclude_files: ['\.gz$']
        tags: ["action"]

    processors:
      - decode_json_fields:
          fields: ["message"]
          process_array: true
          max_depth: 1
          target: ""
          overwrite_keys: true
          add_error_key: false

    output.logstash:
      hosts: ["logstash.beats.svc.cluster.local:5044"]
