---
apiVersion: v1
kind: Service
metadata:
  namespace: beats
  labels:
    app: logstash
  name: logstash
spec:
  selector:
    app: logstash-log-pipeline
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
